# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shapeinspector.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ShapeInspector(object):
    def setupUi(self, ShapeInspector):
        ShapeInspector.setObjectName("ShapeInspector")
        ShapeInspector.resize(919, 563)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ShapeInspector.sizePolicy().hasHeightForWidth())
        ShapeInspector.setSizePolicy(sizePolicy)
        self.centralWidget = QtWidgets.QWidget(ShapeInspector)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(-1, 399, 921, 161))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_control = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_control.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_control.setSpacing(6)
        self.verticalLayout_control.setObjectName("verticalLayout_control")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalSlider_Component_1 = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalSlider_Component_1.sizePolicy().hasHeightForWidth())
        self.verticalSlider_Component_1.setSizePolicy(sizePolicy)
        self.verticalSlider_Component_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalSlider_Component_1.setProperty("value", 50)
        self.verticalSlider_Component_1.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_Component_1.setObjectName("verticalSlider_Component_1")
        self.horizontalLayout.addWidget(self.verticalSlider_Component_1)
        self.verticalSlider_Component_2 = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalSlider_Component_2.sizePolicy().hasHeightForWidth())
        self.verticalSlider_Component_2.setSizePolicy(sizePolicy)
        self.verticalSlider_Component_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalSlider_Component_2.setProperty("value", 50)
        self.verticalSlider_Component_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_Component_2.setObjectName("verticalSlider_Component_2")
        self.horizontalLayout.addWidget(self.verticalSlider_Component_2)
        self.verticalSlider_Component_3 = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalSlider_Component_3.sizePolicy().hasHeightForWidth())
        self.verticalSlider_Component_3.setSizePolicy(sizePolicy)
        self.verticalSlider_Component_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalSlider_Component_3.setProperty("value", 50)
        self.verticalSlider_Component_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_Component_3.setObjectName("verticalSlider_Component_3")
        self.horizontalLayout.addWidget(self.verticalSlider_Component_3)
        self.verticalSlider_Component_4 = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalSlider_Component_4.sizePolicy().hasHeightForWidth())
        self.verticalSlider_Component_4.setSizePolicy(sizePolicy)
        self.verticalSlider_Component_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalSlider_Component_4.setProperty("value", 50)
        self.verticalSlider_Component_4.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_Component_4.setObjectName("verticalSlider_Component_4")
        self.horizontalLayout.addWidget(self.verticalSlider_Component_4)
        self.verticalSlider_Component_5 = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalSlider_Component_5.sizePolicy().hasHeightForWidth())
        self.verticalSlider_Component_5.setSizePolicy(sizePolicy)
        self.verticalSlider_Component_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalSlider_Component_5.setProperty("value", 50)
        self.verticalSlider_Component_5.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_Component_5.setObjectName("verticalSlider_Component_5")
        self.horizontalLayout.addWidget(self.verticalSlider_Component_5)
        self.verticalSlider_Component_6 = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalSlider_Component_6.sizePolicy().hasHeightForWidth())
        self.verticalSlider_Component_6.setSizePolicy(sizePolicy)
        self.verticalSlider_Component_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalSlider_Component_6.setProperty("value", 50)
        self.verticalSlider_Component_6.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_Component_6.setObjectName("verticalSlider_Component_6")
        self.horizontalLayout.addWidget(self.verticalSlider_Component_6)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout_control.addLayout(self.horizontalLayout)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 921, 391))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_Plot = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_Plot.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_Plot.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_Plot.setSpacing(6)
        self.verticalLayout_Plot.setObjectName("verticalLayout_Plot")
        self.verticalLayoutWidget_2.raise_()
        self.verticalLayoutWidget.raise_()
        ShapeInspector.setCentralWidget(self.centralWidget)

        self.retranslateUi(ShapeInspector)
        QtCore.QMetaObject.connectSlotsByName(ShapeInspector)

    def retranslateUi(self, ShapeInspector):
        _translate = QtCore.QCoreApplication.translate
        ShapeInspector.setWindowTitle(_translate("ShapeInspector", "ShapeInspector"))
        self.pushButton.setText(_translate("ShapeInspector", "Reset"))

